#!/bin/bash

set -e

# echo python version
python3 --version

if [ -n "$BASH_VERSION" ]; then
    SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
elif [ -n "$ZSH_VERSION" ]; then
    SCRIPT_DIR="$(cd "$(dirname "${(%):-%x}")" && pwd)"
fi

pip install uv
# The requirements.txt is generated by command:
# uv pip compile pyproject.toml -o ./dev-support/requirements.txt
uv pip sync "${SCRIPT_DIR}/requirements.txt"
# set global solc version which is required by execution-spec-tests
solc-select use 0.8.24 --always-install

# TODO cross platform
#yum install clang snappy snappy-devel zlib zlib-devel bzip2 bzip2-devel lz4-devel
#   wget https://github.com/facebook/zstd/archive/v1.1.3.tar.gz
#   mv v1.1.3.tar.gz zstd-1.1.3.tar.gz
#   tar zxvf zstd-1.1.3.tar.gz
#   cd zstd-1.1.3
#   make && sudo make install
